/* Generated by gen_chat_speech.py. */
#ifndef CHAT_TEST_TIMELINE_H
#define CHAT_TEST_TIMELINE_H
#include "speech_animation.h"
#define CHAT_TEST_CUE_COUNT 5U
static const SpeechCue chat_test_cues[] = {
    {14880U,31200U,14U,23U},
    {42720U,74400U,23U,37U},
    {76320U,83520U,9U,14U},
    {135840U,162240U,23U,37U},
    {165600U,189120U,23U,37U},
};
#endif
