#include "StartupAssets.hpp"
#include <BitmapDatabase.hpp>

const StartupSprite startupSprites[6] = {
    { BITMAP_MANAGED_STARTUP_PIXELS0_ID, 24, 300 },
    { BITMAP_MANAGED_STARTUP_PIXELS1_ID, 24, 300 },
    { BITMAP_MANAGED_STARTUP_PIXELS2_ID, 24, 300 },
    { BITMAP_MANAGED_STARTUP_PIXELS3_ID, 24, 300 },
    { BITMAP_MANAGED_STARTUP_PIXELS4_ID, 15, 94 },
    { BITMAP_MANAGED_STARTUP_PIXELS5_ID, 23, 136 }
};
