"""Generate lossless 48 kHz mono int16 UI assets; run from any directory."""
from pathlib import Path
import struct
import wave

here = Path(__file__).resolve().parent
out = here.parents[2] / "Components" / "Audio"
names = [("nav_tick", "10_nav_tick.wav"), ("menu_enter", "20_menu_enter.wav"),
         ("menu_exit", "21_menu_exit.wav")]
header = ['#ifndef UI_AUDIO_H', '#define UI_AUDIO_H', '#include <stdint.h>']
source = ['/* Generated by aura_assets/audio/ui/convert.py. */', '#include "ui_audio.h"']
for symbol, filename in names:
    with wave.open(str(here / filename), 'rb') as wav:
        assert (wav.getnchannels(), wav.getsampwidth(), wav.getframerate(), wav.getcomptype()) == (1, 2, 48000, 'NONE')
        count = wav.getnframes()
        samples = struct.unpack('<' + 'h' * count, wav.readframes(count))
    header += [f'#define UI_{symbol.upper()}_COUNT {count}U',
               f'extern const int16_t ui_{symbol}[UI_{symbol.upper()}_COUNT];']
    source += [f'const int16_t ui_{symbol}[UI_{symbol.upper()}_COUNT] = {{']
    source += ['    ' + ', '.join(map(str, samples[i:i+16])) + ',' for i in range(0, count, 16)]
    source += ['};']
header += ['#endif']
(out / 'ui_audio.h').write_text('\n'.join(header) + '\n')
(out / 'ui_audio.c').write_text('\n'.join(source) + '\n')
